[server]
address = "0.0.0.0:10001"
llm_mode="openai"
allowed_languages=["ru", "en", "fr", "uk", "ar", "de", "es", "it", "zh", "pl"]
#mode="ollama"

[llm_client.openai]
address="http://localhost:8097"
openai_api_key="sk-or-v1-no-auth"
model_name="tencent.Hunyuan-MT-Chimera-7B.Q8_0"
use_proxy=false
proxy_address="*your proxy url*"

[logger]
level = "debug"
use_loki = "false"
address = "http://0.0.0.0:3110"
